// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using petryankin_daniil_kt_31_21;

#nullable disable

namespace petryankin_daniil_kt_31_21.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20240922104009_CorrectConfig")]
    partial class CorrectConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("petryankin_daniil_kt_31_21.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int4")
                        .HasColumnName("group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("group_name");

                    b.HasKey("GroupId")
                        .HasName("pk_cd_students_group_group_id");

                    b.HasIndex("GroupName")
                        .HasDatabaseName("idx_cd_students_group_group_name");

                    b.ToTable("cd_students_group", (string)null);
                });

            modelBuilder.Entity("petryankin_daniil_kt_31_21.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int4")
                        .HasColumnName("student_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<int>("GroupId")
                        .HasColumnType("int4")
                        .HasColumnName("group_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("middle_name");

                    b.HasKey("StudentId")
                        .HasName("pk_cd_students_student_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("idx_cd_students_group_id");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("idx_cd_students_last_first_name");

                    b.ToTable("cd_students", (string)null);
                });

            modelBuilder.Entity("petryankin_daniil_kt_31_21.Models.Student", b =>
                {
                    b.HasOne("petryankin_daniil_kt_31_21.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
